Added lesson 2
Cherrymood/node-express-course pull request #2
Opened 2024-10-25 18:33 UTC by Cherrymood

2024-10-29 02:53 UTC, mateuspiresl requested changes
Good job on the scripts for `await` and `then` usage!

There are just some small changes you need to do for the PR to be accepted:
- Include the `package.json` file created in the answers directory
- Use `big.txt` from the place it was originally created

If you need any help doing that, please reach out :)

2024-10-29 02:53 UTC, mateuspiresl commented on 01-node-tutorial/answers/writeWithPromisesAwait.js
> +  reader();
Nothing wrong here. It works like it is! I just want to give you some tips:

Remember to use `await` on every async function call, unless you intentionally want to start the function execution and move on without waiting for its completion.

Let's say `readWrite` is called somewhere else with `await`.

```js
await readWrite()
console.log("the file was read")
```

Since there is no await on `reader()`, "the file was read" will be logged to the console before the actual reading completes.

There is a name for that: fire-and-forget. It's when you intentionally start a function execution and move on without waiting for its completion.

2024-10-29 02:53 UTC, mateuspiresl commented on 01-node-tutorial/answers/content/big.txt
You could read this file from the place it was originally created. You would just need to change the path accordingly: `path.join(__dirname, "../content", "big.txt")`.

The .gitignore file from that other content folder will exclude it from git.

2024-10-29 18:41 UTC, Cherrymood commented on 01-node-tutorial/answers/writeWithPromisesAwait.js
> +  reader();
Thanks for your tips. I have tested it, of course your variant is more appropriate.

2024-10-29 18:42 UTC, Cherrymood commented on 01-node-tutorial/answers/content/big.txt
Fixed it

2024-11-06 01:38 UTC, mateuspiresl approved these changes
🙌🏼

2024-11-18 05:41 UTC, merged