Added lesson2-1
Cherrymood/node-express-course pull request #3
Opened 2024-11-01 19:41 UTC by Cherrymood

2024-11-05 00:32 UTC, mateuspiresl requested changes
Nice work!

I've added some suggestions and also pointed a problem on the response when no products are found. Please check the comments for more details.

If there is something not clear, feel free to contact me on Slack!

2024-11-05 00:32 UTC, mateuspiresl commented on 02-express-tutorial/app.js
> +  const idProduct = parseInt(req.params.productID);
Just a naming convention to remember next time: order the names by narrowing down the subject. First "product", which is the main subject, then "ID", which is a property of the product, so the name would be `productId`.

No changes needed here.

2024-11-05 00:32 UTC, mateuspiresl commented on 02-express-tutorial/app.js
> +    res.json("That product was not found.");
A 404 status code is expected in the response, along with a JSON object in the body.

To change the status code, do:

```js
res.status(404)
```

And to change the body to be an object:

```js
res.json({ message: "That product was not found." });
```

You can do both inline if you want:

```js
res.status(404).json({ message: "That product was not found." });
```

2024-11-05 00:32 UTC, mateuspiresl commented on 02-express-tutorial/app.js
> +    }
It's more common to receive an empty list as a response, instead of an error message. `searchProducts` would already have the correct value in this case.

The assignment didn't specify what should be the result if no items are found, so it's up to you to choose. If you stick with the current approach, you just need to fix the response to also have a 404 status code and a JSON object in the body.

2024-11-05 00:32 UTC, mateuspiresl commented on 02-express-tutorial/app.js
> +    }
Same here.

2024-11-05 00:32 UTC, mateuspiresl commented on 02-express-tutorial/public/index.js
👏🏼

2024-11-17 22:40 UTC, Cherrymood commented on 02-express-tutorial/app.js
> +    res.json("That product was not found.");
Yes, that really big mistake.Thanks

2024-11-18 01:52 UTC, mateuspiresl approved these changes
Good to go! 💯

2024-11-18 05:42 UTC, merged