Week 7
Cherrymood/node-express-course pull request #7
Opened 2024-12-20 22:26 UTC by Cherrymood

2024-12-23 21:18 UTC, mateuspiresl requested changes

2024-12-23 21:18 UTC, mateuspiresl commented on 04-store-api/starter/controllers/products.js
> +  let result = Product.find(queryObject);
This should be placed after the if statement for `numericFilters` since the `queryObject` is still being defined tehre.

It will work as is because mongoose will process the query only when it's called with `await`, so the referenced object will have the numeric filters assigned at that time. In any case, you should place the line after that for the following reasons:

1. Clarity: your future coworker reading the code will think that the `numericFilters` are not included in the query when this part is reached;
2. Prevent bugs: someone may make wrong assumptions based on that order.

2024-12-23 21:18 UTC, mateuspiresl commented on 04-store-api/starter/controllers/products.js
> +    result = result.sort("createAt");
```suggestion
    result = result.sort("createdAt");
```

Make sure to test this endpoint without passing the sort param and expecting the response to have an ordered list based on the creation date.

2024-12-23 21:18 UTC, mateuspiresl commented on 04-store-api/starter/middleware/not-found copy.js
Maybe you forgot to delete this - seems like a test.

2024-12-23 21:22 UTC, mateuspiresl commented
It's missing the `populate.js` changes. Make sure you included that in the repository.

2024-12-24 00:48 UTC, Cherrymood commented on 04-store-api/starter/controllers/products.js
> +  let result = Product.find(queryObject);
I got it, thanks!

2025-01-04 20:02 UTC, mateuspiresl approved these changes

2025-01-10 21:29 UTC, merged